#!/bin/bash

qemu-system-arm -kernel zImage-4.1.0 -m 768 -M virt -no-reboot -append "root=/dev/vda2 panic=1 rootfstype=ext4 console=ttyAMA0 rw" -drive file=gentoo-raspi.img,id=root -device virtio-blk-device,drive=root -nographic -netdev tap,id=tap0,ifname=tap0,script=no,downscript=no -device virtio-net-device,netdev=tap0
